In [0]:
import pandas as pd
import numpy  as np
from sklearn.preprocessing import RobustScaler

In [0]:
df = pd.read_csv("vitansigns.csv")

In [0]:
df.head()

HR  SpO2  Pulse  SBP  DBP  MBP
0  55   100     55  113   60   72
1  55   100     55  113   60   72
2  55   100     54  113   60   72
3  55   100     54  113   60   72
4  55   100     49  113   60   72

In [0]:
df.shape

(7296, 6)

In [0]:
train_size = int(len(df) * 0.9)
test_size = len(df) - train_size
train, test = df.iloc[0:train_size], df.iloc[train_size:len(df)]
print(len(train), len(test))

6566 730


In [0]:
print (test)

      HR  SpO2  Pulse  SBP  DBP  MBP
6566  53    99     52   94   46   57
6567  53    99     52   94   46   57
6568  53    99     52   94   46   57
6569  53    99     53   94   46   57
6570  53    99     53   94   46   57
...   ..   ...    ...  ...  ...  ...
7291  53    98     51  106   63   72
7292  53    98     51  106   63   72
7293  53    98     51  106   63   72
7294  53    98     51  106   63   72
7295  53    98     51  106   63   72

[730 rows x 6 columns]


In [0]:
print (test[:])

      HR  SpO2  Pulse  SBP  DBP  MBP
6566  53    99     52   94   46   57
6567  53    99     52   94   46   57
6568  53    99     52   94   46   57
6569  53    99     53   94   46   57
6570  53    99     53   94   46   57
...   ..   ...    ...  ...  ...  ...
7291  53    98     51  106   63   72
7292  53    98     51  106   63   72
7293  53    98     51  106   63   72
7294  53    98     51  106   63   72
7295  53    98     51  106   63   72

[730 rows x 6 columns]


In [0]:
f_transformer = RobustScaler()
f_columns = ['HR', 'SpO2', 'Pulse', 'SBP','DBP','MBP']

In [0]:
f_transformer = f_transformer.fit(train[f_columns].to_numpy())
train.loc[:, f_columns] = f_transformer.transform(train[f_columns].to_numpy())
test.loc[:, f_columns] = f_transformer.transform(test[f_columns].to_numpy())

/usr/local/lib/python3.6/dist-packages/pandas/core/indexing.py:966: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[item] = s
/usr/local/lib/python3.6/dist-packages/pandas/core/indexing.py:966: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[item] = s


In [0]:
print (train)

       HR  SpO2     Pulse       SBP  DBP       MBP
0    -0.5   1.0 -0.333333  2.111111  3.5  2.333333
1    -0.5   1.0 -0.333333  2.111111  3.5  2.333333
2    -0.5   1.0 -0.666667  2.111111  3.5  2.333333
3    -0.5   1.0 -0.666667  2.111111  3.5  2.333333
4    -0.5   1.0 -2.333333  2.111111  3.5  2.333333
...   ...   ...       ...       ...  ...       ...
6561 -1.5   0.0 -1.000000  0.000000  0.0 -0.166667
6562 -1.5   0.0 -1.333333  0.000000  0.0 -0.166667
6563 -1.5   0.0 -1.333333  0.000000  0.0 -0.166667
6564 -1.5   0.0 -1.333333  0.000000  0.0 -0.166667
6565 -1.5   0.0 -1.333333  0.000000  0.0 -0.166667

[6566 rows x 6 columns]


In [0]:
print (test)

       HR  SpO2     Pulse       SBP   DBP       MBP
6566 -1.5   0.0 -1.333333  0.000000  0.00 -0.166667
6567 -1.5   0.0 -1.333333  0.000000  0.00 -0.166667
6568 -1.5   0.0 -1.333333  0.000000  0.00 -0.166667
6569 -1.5   0.0 -1.000000  0.000000  0.00 -0.166667
6570 -1.5   0.0 -1.000000  0.000000  0.00 -0.166667
...   ...   ...       ...       ...   ...       ...
7291 -1.5  -1.0 -1.666667  1.333333  4.25  2.333333
7292 -1.5  -1.0 -1.666667  1.333333  4.25  2.333333
7293 -1.5  -1.0 -1.666667  1.333333  4.25  2.333333
7294 -1.5  -1.0 -1.666667  1.333333  4.25  2.333333
7295 -1.5  -1.0 -1.666667  1.333333  4.25  2.333333

[730 rows x 6 columns]


In [0]:
z1,z2,z3,z4=np.array_split(train, 4)

In [0]:
z1 = z1.to_numpy()
z2 = z2.to_numpy()
z3 = z3.to_numpy()
z4 = z4.to_numpy()
print (z1.shape)
print (z2.shape)
print (z3.shape)
print (z4.shape)

(1642, 6)
(1642, 6)
(1641, 6)
(1641, 6)


In [0]:
import tensorflow as tf
from tensorflow import keras

In [0]:
print (z1.shape[1])
print (z1.shape,z2.shape)

# print (z1,z2)
# print (z1.shape[1])
# print (z1.shape,z2.shape)

# z1 = z1.reshape(-1,1642,6)
# z2 = z2.reshape(-1,1642,6)
# z3 = z4.reshape(-1,1641,6)
# z4 = z4.reshape(-1,1641,6)

print (z1[1000])

size = 1641
z01 = z1[:size].astype(float)
z02 = z2[:size].astype(float)
z01 = z01.reshape(-1, size, 6)
z02 = z02.reshape(-1, size, 6)
print (z01[0][0],z01[0][0])

6
(1642, 6) (1642, 6)
[ 55 100  55  83  46  55]
[ 55. 100.  55. 113.  60.  72.] [ 55. 100.  55. 113.  60.  72.]


In [0]:
model = keras.Sequential()
model.add(
  keras.layers.Bidirectional(
    keras.layers.LSTM(
      units=128,
      input_shape=(size,6)
    )
  )
)
model.add(keras.layers.Dropout(rate=0.2))
model.add(keras.layers.Dense(units=6))
model.compile(loss='mean_squared_error', optimizer='adam')

In [0]:
history = model.fit(
    z01, z02,
    epochs=1000,
    batch_size=32,
    shuffle=False
)

Epoch 844/1000
1/1 [==============================] - 0s 2ms/step - loss: 15.4572
Epoch 845/1000
1/1 [==============================] - 0s 1ms/step - loss: 48.6668
Epoch 846/1000
1/1 [==============================] - 0s 1ms/step - loss: 6.5607
Epoch 847/1000
1/1 [==============================] - 0s 2ms/step - loss: 8.7457
Epoch 848/1000
1/1 [==============================] - 0s 1ms/step - loss: 12.2192
Epoch 849/1000
1/1 [==============================] - 0s 2ms/step - loss: 20.6324
Epoch 850/1000
1/1 [==============================] - 0s 1ms/step - loss: 54.8959
Epoch 851/1000
1/1 [==============================] - 0s 5ms/step - loss: 3.3920
Epoch 852/1000
1/1 [==============================] - 0s 1ms/step - loss: 10.8198
Epoch 853/1000
1/1 [==============================] - 0s 1ms/step - loss: 4.8256
Epoch 854/1000
1/1 [==============================] - 0s 1ms/step - loss: 3.9957
Epoch 855/1000
1/1 [==============================] - 0s 1ms/step - loss: 15.6409
Epoch 856/1000
1/1 [=

In [0]:
z03 = z2[:1].astype(float)
z03 = z03.reshape(-1, 1, 6)
y_pred = model.predict(z03)

In [0]:
print (z03)
###### Real Data #####

[[[54. 99. 53. 89. 46. 56.]]]


In [0]:
print (y_pred)
#### predicted data

[[35.43682  62.06757  34.968437 57.089012 27.855534 35.206226]]


In [0]:
print (z4[:1])

[[ 0.5        -2.          0.33333333  0.77777778  1.25        1.        ]]
